name: test

on:
  workflow_call:
  push:
    branches-ignore:
      - "main" # exclude main branch, since deploy workflow triggers on main, and calls the test workflow inside of it already
    tags-ignore:
      - v* # exclude tags, since deploy workflow triggers on tags, and calls the test workflow inside of it already

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} # per [workflow] x [branch, tag]
  cancel-in-progress: true #  cancel workflows for non-latest commits

jobs:
  suite:
    uses: ./.github/workflows/.test.yml
    with:
      creds-github-app-owner: ehmpathy
      creds-github-app-id: ${{ vars.DECLASTRUCT_GITHUB_TESTAUTH_APP_ID }}
    secrets:
      creds-github-app-private-key: ${{ secrets.DECLASTRUCT_GITHUB_TESTAUTH_APP_PRIVATE_KEY }}
